### ISSUE TITLE
How to avoid name conflicts in components?

### ISSUE THREAD

**Issue by samithaf** [AngularClass/NG6-starter#103]
Please refer to the following use case. 

- home component has a child component call help
- about component has a child component call help

Then I can see about-help component get displayed in home component as well. I was able to solve this issue by prefix the component registration as follows. 

.component('home.help', helpComponent);
.component('about.help', helpComponent);

Is this the standard way of fixing this issue? Any suggestions highly appreciated.

**Comment by fesor** [comment]
1) All components should have at least one dash (i.e. `myComponent`, 'myHome`, `myHelp`)
2) Your components should be reusable. Is there any need of making two different components `about`?
3) prefiex

**Comment by samithaf** [comment]
@fesor please see the following example in Plunker. As you will see both account and portfolio modules has a component call "details". Then Angular throw following error. Seems like even I define component in a module level Angular simply register that in global level.

Error: [$compile:multidir] Multiple directives [details, details] asking for new/isolated scope on: <details> 

[](https://plnkr.co/edit/3IoGG5ALxUpTOr3HH4Fe?p=preview)

**Comment by fesor** [comment]
@samithaf you have two options:

- name components as`portfolioDetails` and `accountDetails`
- use reusable `details` component which allows you to put some custom stuff via multiple transclusion.

Also please note that all custom elements (i.e. components) should contain dash in it's name (`myComponent`, 'xComponent`)

**Comment by fesor** [comment]
@samithaf I'm closing this issue, but before that just additional notes.

In angular 1.x all stuff registered in angular's module system are global, so you should add prefixes to eliminate possibility of name collision. NG6 starter doesn't tries to solve this problem. This problem is solved in ng2, since it relies on ES2015 module system.
