### ISSUE TITLE
https (ssl) serving support

### ISSUE THREAD

**Issue by ranbuch** [AngularClass/NG6-starter#106]
How can I add SSL support while developing (not in production)?
Is it something here?

<code>
gulp.task('serve', () => {
serve({
    port: process.env.PORT || 3000,
    open: false,
    server: { baseDir: root }
  });
});
</code>

Thank you.

**Comment by fesor** [comment]
See documentation for browser sync:

https://www.browsersync.io/docs/options/#option-https
