### ISSUE TITLE
Gulp .spec.js still being included in index.html

### ISSUE THREAD

**Issue by MarkPieszak** [AngularClass/NG6-starter#110]
let paths = {
        js: resolveToComponents('**/*!(.spec.js).js')

^^ This still includes the .spec.js files, it doesn't ignore them. They are still being added into the index.html file.

Tried altering it in many ways, with no luck!

**Comment by fesor** [comment]
> They are still being added into the index.html file.

mmm... why it adds something in index.html in the first place?

**Comment by mcpDESIGNS** [comment]
Well basically it's supposed to get all `.js` files except for `.spec.js`, but it's strange it looks like that syntax **should** be working (even found a stackoverflow about it), but it just doesn't. Does it work for you?
