### ISSUE TITLE
Injecting $controller into ng-mocks specs

### ISSUE THREAD

**Issue by paynoattn** [AngularClass/NG6-starter#112]
Hello,

I have my app up and running in the browser, (https://github.com/paynoattn/angular-paynoattn) but I can't get the spec to work.

I see in the home.spec.js you're just creating a new instance of your class to test your controller, but I'm using a function instead of a class. I can use this for my service though, which is a class, perfectly.

Based on the ng-mocks documentation (https://docs.angularjs.org/guide/unit-testing) you can inject the controller using $controller. Have you gotten this to work with that?

I don't know if this is because I'm using Typescript (it shouldn't because it's just compiling to ES6 for Babel to transpile), or something configured incorrectly but I am seeing the following error:

```
Error: [ng:areq] Argument 'AppController' is not a function, got undefined
      http://errors.angularjs.org/1.5.0/ng/areq?p0=AppController&p1=not%20a%20function%2C%20got%20undefined
```

I can see the controller properly in the spec bundle, so it should be loaded.

Here's my spec:
```
/// <reference path="../typings/tsd.d.ts" />

const expect = chai.expect;

import AppModule from './app.ts';
import AppService from './app-service.ts';

describe('App', function() {
  
  let makeController : Function;
  let makeService : Function;
  let scope : any;
  let $rootScope : any;
  
  beforeEach(angular.mock.module(AppModule));
  
  it('App Module should be properly configured with UI router', function() {
    let module = AppModule
    expect(module.requires[0]).to.equal('ui.router');
  });
  
  describe('Controller', () => {
    
    beforeEach(angular.mock.inject(function ($rootScope, $controller) {
      scope = $rootScope.$new();
      makeController = function() {
        return $controller('AppController',{
            '$scope': scope
        });
      };
    }));
    
    it('AppController should have social media accounts', function() {
      let controller = makeController();
      console.log(controller);
      expect(controller).to.have.property('socialMediaAccounts');
    });
  })
  
  describe('Service', () => {
    
    
   beforeEach(angular.mock.inject((_$rootScope_) => {
    $rootScope = _$rootScope_;
    makeService = () => {
      return new AppService();
    };
  }));
    
    it('AppService should have social media accounts', function() {
      let service = makeService();
      expect(service).to.have.property('socialMediaAccounts');
    })
  })
});
```

As I said, you can see the rest of my project here: https://github.com/paynoattn/angular-paynoattn

**Comment by paynoattn** [comment]
Okay, wow.

Easy fix, apparently.

```
beforeEach(angular.mock.module(AppModule));
```


should be

```
beforeEach(angular.mock.module('paynoattnApp'));
```

I have no idea how this is working though, since you also apparently need 

```
let module = AppModule
```

For everything to work correctly. ???

**Comment by fesor** [comment]
I think that `AppModule` is instance of module, not it's name:

```javascript
import angular from 'angular';

export default angular.module('app', []);
```

so you should use:

```javascript
beforeEach(angular.mock.module(AppModule.name));
```

Or you could export just module name (This is what I do in my projects):

```
export default angular.module('app', []).name;
```

**Comment by paynoattn** [comment]
I see 
```
beforeEach(angular.mock.module(AppModule.name));
```
 works as well. Good tip. :+1:
