### ISSUE TITLE
ReferenceError: 'Symbol' is undefined in IE 11

### ISSUE THREAD

**Issue by ranbuch** [AngularClass/NG6-starter#114]
Everything works fine in all the browsers including Edge. In IE 11 (and possibly more versions) I'm getting the error:
ReferenceError: 'Symbol' is undefined

I haven't changed the gulp and webpack files. is the bable transpiling working or do I have to do something for him to work?

Thank you.

**Comment by ranbuch** [comment]
Solved:
https://babeljs.io/docs/usage/polyfill/

**Comment by fesor** [comment]
@ranbuch closing this. Feel free to ask more related questions about polyfills.

**Comment by scriptrance** [comment]
Still getting the issue
