### ISSUE TITLE
babel-register failed

### ISSUE THREAD

**Issue by bdenham** [AngularClass/NG6-starter#117]
When running gulp default, I get this: "Failed to load external module babel-register". Can I safely ignore this? Or do I need to update/modify something?

**Comment by fesor** [comment]
@bdenham please provide gulp and node versions.

**Comment by ok2ju** [comment]
@fesor same issue. 
node version: v 5.9.1
gulp cli: 1.2.1
local gulp version: 3.9.1

**Comment by ok2ju** [comment]
@bdenham i just install older version of `webpack-dev-middleware` (1.4.0) and it works.
https://github.com/webpack/webpack-dev-middleware/issues/82

**Comment by webdevua** [comment]
node version: v5.4.1
local gulp version: 3.9.1

**Comment by fesor** [comment]
Ok, so the problem is broken commit in `webpack-dev-middleware`. It already has been reverted and should be published on NPM soon.

Please watch this issue: https://github.com/webpack/webpack-dev-middleware/issues/82

**Comment by webdevua** [comment]
@fesor thanks for quick feedback

**Comment by bdenham** [comment]
Thanks, everyone!
