### ISSUE TITLE
gulp webpack deletes the whole app

### ISSUE THREAD

**Issue by hwclass** [AngularClass/NG6-starter#122]
Hi all,

After initializing the command "gulp webpack", it removes the whole main app files (components and common) leaving the new components created with the command "gulp component --name foo".

Thanks,

Barış

**Comment by fesor** [comment]
Can you provide more details?

**Comment by fesor** [comment]
@hwclass ping.

**Comment by hwclass** [comment]
Hey, I think this was just an exceptional state for the boilerplate. After then, I had never come face to face such a problem.

Thanks @fesor.
