### ISSUE TITLE
files changes no refresh the browser

### ISSUE THREAD

**Issue by enzonotario** [AngularClass/NG6-starter#126]
Hi, SORRY FOR MY ENGLISH and my ignorance, but..
I run:
`gulp`

And when i change some file, the browser not refresh.
In the console of FF i see:
```
The connection to ws://localhost:3000/browser-sync/socket.io/?EIO=3&transport=websocket&sid=JpLNuFhzJSiRxQA_AAAD was interrupted while the page was loading. browser-sync-client.2.11.2.js:1:27982
The connection to http://localhost:3000/__webpack_hmr was interrupted while the page was loading. vendor.bundle.js:666:16
unreachable code after return statement vendor.bundle.js:64916:9
[HMR] connected
```

Can someone help me please?, thanks!

**Comment by enzonotario** [comment]
well, now it works, I don't know why...
sorry.

**Comment by mqliutie** [comment]
I have the same problem. It don't work for me

**Comment by mqliutie** [comment]
Ok, when I add space to file browser doesn't refresh. If I add `console.log(123)`, It works!
Can it check if I have added new content?

**Comment by enzonotario** [comment]
for me, it sometimes work, and sometimes not work... when it not work, I close all and run gulp again, until it works (1 or 2 times)...
