### ISSUE TITLE
gulb don't work

### ISSUE THREAD

**Issue by jensklose** [AngularClass/NG6-starter#128]
I use your documentation and run in:
```
    NG6-starter (master) $ gulp
    [22:42:06] No gulpfile found
```
Why don't you kick gulp and migrating all to npm scripts?

**Comment by fesor** [comment]
Hi, @jensklose 

> No gulpfile found

Please provide your `gulp` version. It look's like it doesn't try to load `gulpfile.babel.js`.

> Why don't you kick gulp and migrating all to npm scripts?

NPM scripts are great for dealing with simple routine, but:

 - we have component code-generation command in it
 - we have some path configuration in it, so it will be easier to change

This is two main reasons why we are using gulp. Personally I also use gulp for build and deploy tasks. I could use bash for it, but I just don't want to.

I more like the idea of creating yoman generator from this starter. This would allow users to chose.

**Comment by jensklose** [comment]
Ok, thx.
```node_modules/.bin/gulp``` does the work. This could be put in an npm start script.

I don't update and deal with the globals. ;)
