### ISSUE TITLE
I'm noob, want to know how this thing finds node_modules

### ISSUE THREAD

**Issue by robguy21** [AngularClass/NG6-starter#131]
How exactly are node_modules being imported and made available to the app? 

And how can I get bower_components available to my app?

First time working with webpack so I don't know if this is some crazy webpack magic but I also can't find where you are including the angular.js file from node_modules/

This problem is arising because of two things-

In a production environment I'd like to build a main.js and server angular and all my other dependancies from there [obviously also minify it].

I want to use some bower components that aren't available to npm, how can I use these in my angular app?

**Comment by slurmulon** [comment]
Regarding your `bower_components` issue, you should be able to utilize `resolve.alias` to achieve this: http://webpack.github.io/docs/configuration.html#resolve-alias

**Comment by robguy21** [comment]
@slurmulon awesome thanks man!
