### ISSUE TITLE
Unit tests for the component should be using $componentController

### ISSUE THREAD

**Issue by samithaf** [AngularClass/NG6-starter#133]
Form angular 1.5 we can use $componentController for unit test the controllers. It will be nice if we can update the repo to use it.

https://docs.angularjs.org/api/ngMock/service/$componentController

**Comment by bastianwegge** [comment]
@samithaf why don't you make a pull-request? :)

**Comment by samithaf** [comment]
@bastianwegge that is not a problem. I am already using it on my current project at work. Will do it soon.

**Comment by samithaf** [comment]
@fesor @bastianwegge Pull-request created. https://github.com/AngularClass/NG6-starter/pull/159

**Comment by fesor** [comment]
Closing since #159 landed.
