### ISSUE TITLE
Encountered Error: [$injector:unpr] Unknown provider: tProvider <- t on built asset

### ISSUE THREAD

**Issue by nesiri** [AngularClass/NG6-starter#138]
Hey guys,

I am experiencing the following error on minified assets for JSPM version (app.min.js)?

`Error: [$injector:unpr] Unknown provider: tProvider <- t`

I do not encounter the same problem on app.js though.

**Comment by fesor** [comment]
you should annotate your injectables (by hand or using ngAnnotate)

**Comment by nesiri** [comment]
Thanks that solved it
