### ISSUE TITLE
Sample of directives

### ISSUE THREAD

**Issue by sitorush** [AngularClass/NG6-starter#140]
Hi.. Is there an example how to create a directive? I need a directive not a component. I need to do animations and lots of DOM manipulations.

Thanks

**Comment by kotmatpockuh** [comment]
@sitorush any ideas?

**Comment by sitorush** [comment]
Yep, look at the example app here: https://github.com/AngularClass/NG6-todomvc-starter/tree/master/src/app/components/todoTextInput
