### ISSUE TITLE
Size of vendor.bundle.js is quite large

### ISSUE THREAD

**Issue by the-fool** [AngularClass/NG6-starter#143]
Even after uglification, the size of the vendor.bundle.js is **293 kB**.  Is this right?  I know there are polyfills and such added on -- but I feel like something is wrong.

If ~300kB is the baseline for a Babel + Angular app, what can be done to lighten the load?

**Comment by fesor** [comment]
This starter includes babel-polyfill by default, but you can remove it and import only those polyfils that you need.

Baseline for babel + angular + uglifyjs is + gzip ~60Kb for `vendor.bundle.js`. This is without polyfils and uiRouter.

**Comment by fesor** [comment]
@the-fool please let me know if you solved problem.

**Comment by phil-lgr** [comment]
I am a newb with Babel, could you kindly explain where/how to import certain polyfills ?

**Comment by phil-lgr** [comment]
Got it, it is define as entry point, I commented it and now size is acceptable thanks @fesor 
```
entry: [
    //'babel-polyfill',
    path.join(__dirname, root, 'app/app.js')
  ],
````

**Comment by phil-lgr** [comment]
@fesor could you explain how to remove it properly ? I am new with ES6 and Babel.

**Comment by the-fool** [comment]
Yes - very much! Thank you for the kind help.

**Comment by fesor** [comment]
Search for `babel-polyfil` in gulpfile and just remove it. Also check this: https://github.com/zloirock/core-js#commonjs

**Comment by phil-lgr** [comment]
Yes I saw it yesterday night! Thank you for pointing it out.
