### ISSUE TITLE
How to inject dependencies such as $http ?

### ISSUE THREAD

**Issue by PedroEsperanca** [AngularClass/NG6-starter#145]
Sorry for the noob question, but I feel like I've been trying to figure out how to inject dependencies into services or controllers for too long.

The examples leave no doubt about how to inject created services but can't find an example on how to use core angular services.

Thanks!
Pedro

**Comment by phil-lgr** [comment]
It's the same approach with controllers or services, you have to use the `"ngInject"` syntax as this boilerplate uses https://github.com/olov/ng-annotate

```
class searchService {
  constructor($log) {
    "ngInject";
    this.$log = $log;
  }

  doSomething() {
    this.$log('hey');
  }
export default searchService;
```

**Comment by PedroEsperanca** [comment]
thanks @phil-lgr !

**Comment by ramytamer** [comment]
How can i call `doSomething()` from constructor?

**Comment by pziegler** [comment]
you can also use the following style
````
class searchService {
  constructor($log) {
    this.$log = $log;
  }

  doSomething() {
    this.$log('hey');
  }
searchService.$inject = ['$log'];
export default searchService;
