### ISSUE TITLE
How to disable autoreload ?

### ISSUE THREAD

**Issue by ramytamer** [AngularClass/NG6-starter#164]
I know it's a dump question, but i couldn't manage to disable watching file so the tab reloads each time i save a file.

Thanks

**Comment by pziegler** [comment]
any good reason why you would want to do this?

**Comment by ramytamer** [comment]
I am using it on a pretty slow computer & i save every 2 seconds :sweat_smile: ; so i want to manually refresh the page

**Comment by samithaf** [comment]
Add this to BS config.

```
    snippetOptions: {
      rule: {
        match: /qqqqqqqqq/,
      },
    },
```

**Comment by bmsdave** [comment]
@ramytamer,
```
// Adds webpack HMR support. It act's like livereload,
// reloading page after webpack rebuilt modules.
// It also updates stylesheets and inline assets without page reloading.
new webpack.HotModuleReplacementPlugin()
```
just commented  "new webpack.HotModuleReplacementPlugin()" in webpack.dev.config.js

**Comment by fesor** [comment]
@ramytamer could I close this issue?

**Comment by fesor** [comment]
Closing this, feel free to ask here if you have any additional questions.
