### ISSUE TITLE
webpack.config.js  - devtool

### ISSUE THREAD

**Issue by blowsie** [AngularClass/NG6-starter#170]
Im new to webpack, but based on the documentation (https://webpack.github.io/docs/configuration.html#devtool)

Should the webpack.config.js not be 

```
devtool: 'source-map',
```

instead of 
```
devtool: 'sourcemap',
```

**Comment by pziegler** [comment]
there is a PL for this already

**Comment by blowsie** [comment]
https://github.com/AngularClass/NG6-starter/pull/153
