### ISSUE TITLE
How to include jquery-ui ?

### ISSUE THREAD

**Issue by ramytamer** [AngularClass/NG6-starter#171]
I want to include jquery-ui in my project.

I installed it via npm (npm install --save jquery-ui) it didn't work because of some error with the images, i found a solution to install this package (jquery-ui-bundle) it didn't work also as expected.

I don't know the best way to import or use package like jquery-ui with bunch of css & images (assets) files and import them via javascript.

Thanks

**Comment by bmsdave** [comment]
@ramytamer, show traceroute of exceptions

**Comment by sabareeshkk** [comment]
Try loading it using Webpack.
expose-loader may help you

**Comment by edin-m** [comment]
Just import it...

```
import $ from 'jquery';
import '../../../node_modules/jquery-ui/ui/widgets/draggable';
```

**Comment by fesor** [comment]
@edin-m why not `import 'jquery-ui/ui/widgets/draggable`?

**Comment by ramytamer** [comment]
I ended up installing **jquery-ui-bundle** alongside with **jquery** of-course via npm and importing it like this:

```javascript
import 'jquery';
import 'jquery-ui-bundle';
```
