### ISSUE TITLE
Debugging an NG6-Starter application

### ISSUE THREAD

**Issue by blowsie** [AngularClass/NG6-starter#196]
Hi, 

Whenever my application throws an error, in the console it shows it coming from `angular.js` and not the controller file where the error actually originated.

This makes for some very difficult debugging.

![image](https://cloud.githubusercontent.com/assets/308572/20829027/36e565d4-b872-11e6-845a-935f38cd890a.png)

Is there a way the debugging information can be improved to show the source of the error?

**Comment by fesor** [comment]
> This makes for some very difficult debugging.

Yep, this is pretty common problem. You could use solutions [like this](http://jsfiddle.net/SanderElias/Y45Ag/) to make stack traces more readable. You could also try to use [zone.js](https://github.com/angular/zone.js/) with long stack traces.
