### ISSUE TITLE
How to provide $state resolve in controller unit test?

### ISSUE THREAD

**Issue by ttbarnes** [AngularClass/NG6-starter#199]
How can you provide a mock state resolve? I've been trying various approaches (injecting, $provide, manual mocking inside a scenario) and nothing is working. How can you do it? I'm stumped.

EG my state resolve:

```
$stateProvider
    .state('someState', {
      url: '/p/:id',
      resolve: {
        someData: (myService, $stateParams) => {
          return myService.getTheData($stateParams.id);
        }
      },
      controller: ['$scope', 'someData', ($scope, someData) => {
        $scope.profile = someData.data;
      }],

      template: '<some-page profile="someData"></some-page>'
    });
```

simplified spec: 
```
beforeEach(function(){
  window.module(Services.name);
  window.module(($provide) => {
    $provide.value('profile', { name: 'testing' }  );
  });
});

beforeEach(inject((_$rootScope_, _$q_, _$httpBackend_, myService) => {
  $rootScope = _$rootScope_;
  $q = _$q_;
  deferred = _$q_.defer();
  $httpBackend = _$httpBackend_;
  myService = myService;
  scope = $rootScope.$new();
  scope.vm = $rootScope.$new();
  spyOn(myService, 'getTheData').and.callThrough();
  makeController = () => {
    return new MyController(myService, {$scope: scope, profile: mockProfile });
  };
}));

describe('Controller', () => {

  it('should have a name property', () => {
    // let vm = makeController(myService, {$scope: scope, profile: mockProfile});
    let vm = makeController();
    expect(vm.profile.name).toBeDefined();
  });

});
```

**Comment by fesor** [comment]
You don't need controller. You could just pass resolved values directly to component:

https://ui-router.github.io/guide/ng1/route-to-component#migrate-to-components

So you can just test resolvers and components independently.

**Comment by ttbarnes** [comment]
Actually i'm pretty sure I do need controller. I'm passing resolve data into controller, have conditions for the template, in the controller that are dependant on the resolve data. Therefore I would like to provide mock $state resolve data to be used in controller unit test. If you have resolve data dependancy in controller and it's not received, it blocks any proceeding tests.

**Comment by fesor** [comment]
> have conditions for the template, in the controller that are dependant on the resolve data

Can you show some example?

**Comment by ttbarnes** [comment]
Thanks @fesor  - just seen your reference here:  https://github.com/AngularClass/NG6-starter/issues/12#issuecomment-266069441 which looks great, i'll try it out :)

Here is what I have been trying to do. Would be great to have a solution for this, whilst I look at migrating to the component approach.

state:
```
.config(($stateProvider) => {
  'ngInject';
  $stateProvider
    .state('profile', {
      url: '/p/:id',
      template: '<profile-public profile="profile"></profile-public>',
      resolve: {
        profile: (myService, $stateParams) => {
          return myService.getProfile($stateParams.id);
        }
      },
      controller: function($scope, profile){
        $scope.profile = profile.data;
      }
    });
})
```

controller:
```
class ProfileController {
  constructor() {
    'ngInject';
    this.heading = this.profile.name;   //controller unit tests fails because of no data from profile resolve
  }
  //...
}

```

**Comment by fesor** [comment]
You may use `$onInit` hook to do so:

```javascript
class ProfileController {
    $onInit() {
        this.heading = this.profile.name;
    }
}
```

But I usually do this on bindings changes:

```javascript
class ProfileController {
    set profile(profile) {
        this.$profile = profile;
        this.heading = profile.name;
    }
}
```

**Comment by ttbarnes** [comment]
doing this on bindings changes works great thanks @fesor 

You just have to set a mock profile in controller spec, eg:

```
describe('Controller', () => {
    it('should have a heading', () => {
      let controller = makeController();
      controller.$profile = mockProfile;
      expect(controller.$profile).toBeDefined();
      expect(controller.heading).toEqual(controller.$profile.name);
    });
  });
```

I tried using the components approach (without resolvers) you mentioned, but wasn't working for me right away. Have to focus on other things, but plan to spend more time looking at this 👍
