### ISSUE TITLE
Deploy to production?

### ISSUE THREAD

**Issue by mcblum** [AngularClass/NG6-starter#200]
Hello!  

So we're ready to deploy our first app build with the NG6-starter and we're having some issues deploying. Three current issues:

1. Where should I look to figure out how to turn all of the `blob:https://example.com/asdeasdasd-asdasdasd-asdasdasd` into a single css file?

2. Any idea why we might be seeing this error when deploying? We're using a shared host:
```
 DEBUG [da7d3fda]       EPEERINVALID

 DEBUG [da7d3fda]        angular-material@1.1.1 requires a peer of angular-animate@>=1.3 <1.6 but none was installed.

 DEBUG [da7d3fda]       npm WARN 

 DEBUG [da7d3fda]       EPEERINVALID

 DEBUG [da7d3fda]        angular-material@1.1.1 requires a peer of angular-aria@>=1.3 <1.6 but none was installed.

 DEBUG [da7d3fda]       /usr/lib/node_modules/gulp/node_modules/liftoff/node_modules/findup-sync/node_modules/glob/sync.js:283

      if (this.strict) throw er
                       ^
Error: EACCES: permission denied, scandir '/home'
```
3. For whatever reason when using the dev webserver it works great, but serving the site from the dist folder has no htaccess and I'm not sure how to actually make it work with gulp.

Thank you for this project -- we've learned a ton by using it.

**Comment by mocsharp** [comment]
Same here.  I ran the following but it only outputs the vendor bundle script and not my scripts.
`webpack -p --config .\webpack.dist.config.js`

**Comment by diegochavez** [comment]
Hi guys are you running?
`gulp webpack` 
This command creates a /dist directory on the route of your project, and have all scripts minified.

**Comment by mcblum** [comment]
@diegochavez hey man -- just saw this. I had forgotten I had opened this issue. I'm closing because I think it was completely unrelated to NG6 Starter and was actually a server issue.
