### ISSUE TITLE
I must use $apply() to see changes...?

### ISSUE THREAD

**Issue by edin-m** [AngularClass/NG6-starter#203]
I have simple component/controller/html for "file manager" so:

html:
```html
  <div>
    {{ ($ctrl.wickedSick || {}) | json }}
  </div>
```

component:
```javascript
export default {
  restrict: 'E',
  bindings: {},
  template,
  controller
};
```

and controller:
```javascript
class FileManagerController {
  constructor($scope) {
    this.wickedSick = 'wicked sick !!! 123';
    setTimeout(() => {
      this.wickedSick = 'new value';
      $scope.$apply();
    }, 5000);
  }
}
```

If I don't have `$scope.$apply()` I don't se resulting changes. And I would like not to use `$apply()` manually... Am I doing something wrong?

**Comment by fesor** [comment]
you should wrap all async functions to meka them start digest cycle. In case of `setTimeout` angular provides you `$timeout` service which handles digest for you.
