### ISSUE TITLE
missing use strict mode

### ISSUE THREAD

**Issue by daton89** [AngularClass/NG6-starter#208]
In client/app/*.js files there isn't the starter "use strict" 

in ES6 it is required but there is some reason for which may be missing?

**Comment by tytskyi** [comment]
@daton89 

> Module code is always strict mode code.

http://www.ecma-international.org/ecma-262/6.0/#sec-strict-mode-code

Which means you don't need to put it manually

**Comment by fesor** [comment]
Closing this since @tytskyi already provided right link.
