### ISSUE TITLE
Webpack sometimes doesn't recompile files on watching.

### ISSUE THREAD

**Issue by namerci** [AngularClass/NG6-starter#210]
I have latest cloned version of NG6-starter and in PHPStorm when I make changes in files and tries to save it by CTRL + S, webpack nothing do. Sometimes I need to make change in one of file (doesn't matter which one) and again save file. If still not work, then need to repeat process.

It always work after few tries :)

NodeJS: v7.5.0
NPM: v4.1.2
Windows 10 PRO, 64 bit

**Comment by FarhadG** [comment]
This is exactly the same issue we're having and we, continually, need to pseudo-save files to have webpack pick up changes.

Would love to see what kind of fix we can get in for this...

**Comment by shall-git** [comment]
Just turn off 'Safe write' setting in PHPStorm. Follow these steps
https://stackoverflow.com/a/34225091/6396555

**Comment by FarhadG** [comment]
^ Will give that a try...

**Comment by fesor** [comment]
Closing this since issue is related to webpack. If you have this problem please check webpack [documentation](https://webpack.github.io/docs/troubleshooting.html) or found/write issue in their repository.
