### ISSUE TITLE
Possibility to turn off minification

### ISSUE THREAD

**Issue by kotmatpockuh** [AngularClass/NG6-starter#222]
Is it possible to turn off all minification and obfuscation of app.js & vendor.js and any style files?

**Comment by xandyalexandrec** [comment]
I'm having the same issue. @kotmatpockuh did you find a solution?

**Comment by fesor** [comment]
Just remove `UglifyJsPlugin` from `webpack.dist.config.js`.

**Comment by fesor** [comment]
Closing this.
