### ISSUE TITLE
Service inject problem

### ISSUE THREAD

**Issue by IdaszakDaniel** [AngularClass/NG6-starter#230]
Hi, 
My Service is not working in component. Am I doing something wrong? I did everything exactly like https://github.com/AngularClass/NG6-todomvc-starter
My repository:
https://github.com/IdaszakDaniel/MRTask

**Comment by fesor** [comment]
https://github.com/IdaszakDaniel/MRTask/blob/master/client/app/components/about/about.controller.js#L13

Your service returns promise.
