### ISSUE TITLE
Dockerfile inclusion

### ISSUE THREAD

**Issue by bernardocs** [AngularClass/NG6-starter#235]
Hey guys!

I use this project as boilerplate of my project and I'm pretty satisfied with it.

I've been working on a `Dockerfile` for the project and wondered if anybody here have ever thought of creating one already. And if you did, why it was not already included? 

I did a quick search through the issues section and didn't find any mention of it. I'm no Docker specialist as I'm using this oportunity to effectively learn more about it, but It would definitelly save the pain of going through known issues. 😄

**Comment by gdi2290** [comment]
if you make a PR I wouldn't mind merging it

**Comment by bernardocs** [comment]
I'm on it! 😄 

But as I said, I'm about Docker while I'm on it... 
So, I would appreciate some review!

I'll link the Pull Request here as soon as I make it work somehow...

**Comment by bernardocs** [comment]
It's on! #236

**Comment by gdi2290** [comment]
thanks, merged
