### ISSUE TITLE
Adding SEO support

### ISSUE THREAD

**Issue by agarwalvinit** [AngularClass/NG6-starter#238]
Hi Guys,
Thanks for creating this boilerplate app. It would be nice if there could be SEO support as I haven't seen any seo supported boilerplate. Again just a suggestion. Thanks !

**Comment by fesor** [comment]
This is very depend on project. AngularJS doesn't have any ability to preform server side rendering. You could use https://github.com/prerender/prerender for this, but I don't think that we could generalize such solutions so it will appear in starter.
