### ISSUE TITLE
Repeating of dependencies

### ISSUE THREAD

**Issue by Rush** [AngularClass/NG6-starter#28]
I really really hate this pattern when you have to list your dependency twice

```
import angular from 'angular';
import Home from './home/home';
import About from './about/about';

let componentModule = angular.module('app.components', [
  Home.name,
  About.name
]);

export default componentModule;
```

In AMD I used to do this:

```
var angular = require('angular');
var moduleId = require('module').id;
var componentModule = angular.module(moduleId, [
  require('./home/home'),
  require('./about.name')
]);
return moduleId;
```

Any ideas how to improve it in ES6?

**Comment by gdi2290** [comment]
@Rush this is due to es6 and angular1's di system. With ES6 you're forced to keep the imports at the top level

**Comment by Rush** [comment]
@gdi2290 thanks for the reply, any ideas how to go around this? I am considering using one big fat angular module but that would take a lot of refactoring unfortunately. :-(

**Comment by gdi2290** [comment]
@Rush with webpack you can still use require so
```es6
var componentModule = angular.module(moduleId, [
  require('./home/home').name,
  require('./about.name').name
]);
```

**Comment by Rush** [comment]
I think I am already in love with SystemJS :-)

**Comment by gdi2290** [comment]
you might be able to do the same with systemjs I'm not sure

**Comment by fesor** [comment]
Well, since you don't need module instance anywhere alse than in .module.js, you can simly export module name.

```
import home from './components/home/home.module.js'
import angular from 'angular'

angular.module('app', [
    home
]);
```

**Comment by fesor** [comment]
Closing this for now.
