### ISSUE TITLE
SCSS support 

### ISSUE THREAD

**Issue by dimpu** [AngularClass/NG6-starter#32]
It would be great if we have scss support.

**Comment by fesor** [comment]
scss vs less vs stylus: fight

**Comment by gdi2290** [comment]
scss is the most popular one to be honest. PostCSS is the next to be widely adopted if trends continue

**Comment by wgorder** [comment]
This is a great seed project!  We used this seed as a starting point and enhanced it in a number of ways.  I will probably open some PR's when I get some time and you can decide if you want to take any of them.  I figured since it is meant to be used for training and not necessarily for production applications you will not want all the stuff I did though.

That said we just added loaders for all 3 and the dev can use what they want :)

**Comment by liorhar** [comment]
any chance someone is posting an example of this starter with scss support? Not suggesting scss is better, that's just what we use and I'm having troubles wiring all the configs to support that.

**Comment by fesor** [comment]
https://github.com/jtangelder/sass-loader - just read documetation.

**Comment by m-j** [comment]
Any solution for JSPM version?

**Comment by capaj** [comment]
@m-j scss is impossible to compile in the browser. I could whip up a simple build script and hook it up into a watcher. Maybe one day if I have time...

**Comment by m-j** [comment]
@capaj Thx. So in other words: if we want to use scss we need to compile it in gulp and then serve our app from target/dev folder (or however you call it) instead of just serving src.

**Comment by capaj** [comment]
@m-j yes

**Comment by gebidesign** [comment]
Made a fork and replaced stylus with scss. Here's the link, hope it will help https://github.com/gebidesign/NG6-starter-sass

**Comment by PenAndPapers** [comment]
hi, I cant figure out why its not generating .scss file instead it still generating .styl. Ive changed the webpack.config.js to  **{ test: /\.scss$/, loader: 'style!css!sass' }** and also installed node-sass and sass-loader.

**Comment by tucq88** [comment]
Thanks @bivainis . This should be added in README

**Comment by fesor** [comment]
@tucq88 I think that it's better to replace stylus with scss. Anyway angular2 starter uses scss instead of stylus.

**Comment by fesor** [comment]
I prepare PR to switch from stylus to scss: #188

**Comment by fesor** [comment]
Since #188 is landed, I should probably close this issue.
