### ISSUE TITLE
lack of production settings 

### ISSUE THREAD

**Issue by mydearxym** [AngularClass/NG6-starter#39]
amazing work!

but there is no method for minify/uglify code  support ...

**Comment by verdverm** [comment]
@mydearxym 

This is relatively easy with a few steps. The main issues is that you need safe dependency injection for Angular to make it through the minification process without mangling names to all error.

Maybe we can turn it into a PR

---
#### step 1
I suggest adding `ng-strict-di` to avoid headaches down the line

in `index.html` 
```
...
<body ng-app="app" ng-cloak ng-strict-di>
...
```

#### step 2
Add dependency inject to the module.config calls (home.js, about.js, any others...)
```
.config(['$stateProvider', ($stateProvider) => {
...
}])  // <--- don't forget the closing ']'
```
#### step 3
For controllers, you need to do dependency injection as follows
```
// note: I'm using ngRedux with angular :]

class HomeController {
    constructor($ngRedux, $scope) {
        this.name = 'home';

        let unsubscribe = $ngRedux.connect(
            this.mapStateToThis
        )(this);

        $scope.$on('$destroy', unsubscribe);
    }

    mapStateToThis(state) {
        return {
            globalState: state,
        };
    }
}

HomeController.$inject = ['$ngRedux', '$scope'];

export default HomeController;
```

#### step 4
Update the gulp file. This requires a few changes.

##### step 4-a
rename `webpack` to `webpackStream`

includes should now resemble
```
import gulp     from 'gulp';
import gutil    from 'gulp-util';
import webpack  from 'webpack';
import webpackStream  from 'webpack-stream';
...
```

only line I found in the original was this one
```
    .pipe(webpackStream(require('./webpack.config')))
```

##### step 4-b
add the following code (modified from [here](https://github.com/webpack/webpack-with-common-libs/blob/master/gulpfile.js) )

```
// Production build
gulp.task("build", ["webpack:build"]);

gulp.task("webpack:build", function(callback) {
  // modify some webpack config options
  var myConfig = Object.create(require('./webpack.production.config'));
  if (!myConfig.plugins){ 
    myConfig.plugins = [];
  }
  myConfig.plugins = myConfig.plugins.concat(
    new webpack.DefinePlugin({
      "process.env": {
        // This has effect on the react lib size
        "NODE_ENV": JSON.stringify("production")
      }
    }),
    new webpack.optimize.DedupePlugin(),
    new webpack.optimize.UglifyJsPlugin()
  );

  // run webpack
  webpack(myConfig, function(err, stats) {
    if(err) throw new gutil.PluginError("webpack:build", err);
    gutil.log("[webpack:build]", stats.toString({
      colors: true
    }));
    callback();
  });
});
```

##### step 4-c
make sure you have any additional dependencies.

`npm install --save gulp-util` (in my case)


#### step 5
make a `webpack.production.config.js`

I copied the existing one and changed the output name to `bundle.min.js`

#### Finally !!!
run `gulp build` and you have your production ready file.

The NG6-starter goes from 1.3M to 200K

My own starter project [starterKit](https://github.com/verdverm/starterKit) is now 20% of the originial size... a 5X reduction woot woot!

I'm not sure why, but the sourcemap files get much bigger in the process


Hope this helps someone!

**Comment by mydearxym** [comment]
thanks @verdverm !

**Comment by fesor** [comment]
Reopening this since currently only ngAnnotate available and this will be very usefull to have more ready-to-use webpack configuration.

**Comment by fesor** [comment]
I added prod config for webpack, so bundle size is ~200kb now.
