### ISSUE TITLE
how angular-es6 inheritance should be provided? 

### ISSUE THREAD

**Issue by kirillstepkin** [AngularClass/NG6-starter#43]
Parent-child relationship between controllers, directives.
In es5-angular these relationship are implemented using scope and scope inheritance.
Now we use classes, extends, super methods.

But my problem is when I create directive class and then controller class that uses some data from directive class, controller class will be a child of directive class, but in this case directive class constructor will be called 2 times, so I got an error : Multiple directives [searchBar (module: ontour), searchBar (module: ontour)] asking for template on.

It's a big question, i can't find any examples of it in this boilerplate and articles on web.

**Comment by fesor** [comment]
Well... you probably shouldn't use inheritance, use composition/decoration instead. To DRY stuff you can just move all reusable logic to separate services/directives.

**Comment by fesor** [comment]
@kirillstepkin you can provide your use cases when you need inheritance and maybe we can provide you examples or solutions using composition/decoration.

**Comment by fesor** [comment]
@kirillstepkin can I close this issue?
