### ISSUE TITLE
Cannot find module 'chai' immediately after setup

### ISSUE THREAD

**Issue by jbcpollak** [AngularClass/NG6-starter#48]
I followed the setup instructions (clone then `npm install`), and when I run gulp, everything starts fine. But if I run `npm test`, I get this error:

```
module.js:338
    throw err;
    ^

Error: Cannot find module 'chai'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.require.resolve (module.js:388:19)
```

I see karma-chai is a dependency, and it is installed in node_modules.

I am using node v4.1.2 and npm 3.3.6.

**Comment by fesor** [comment]
The reason is that `chai` module listed in `karma-chai` as peer dependency.

With NPM3 you'll get this warnings:

```
npm WARN peerDependencies The peer dependency chai@* included from karma-chai will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
```

So what you need to do is just install chai locally for your project:

```
npm install --save chai
```
