### ISSUE TITLE
How to create a directive with attributes?

### ISSUE THREAD

**Issue by rwillmer** [AngularClass/NG6-starter#50]
I've been struggling with this all weekend... How do you use this style of component definition with a custom directive which takes an attribute? That is...

<foo bar='hello'></foo>

Any pointers to a working example would be great...

**Comment by fesor** [comment]
well... I handle attributes in `link` (or just using bindToController if needed) and then pass values to controller.

```javascript
return {
    template,
    controller,
    controllerAs: 'vm',
    scope: {},
    bindToController: {},
    link: function (scope, el, attr, vm) {
         attr.$observe('foo', (value) => {
              ctr.setFoo(value);
         });
    }
}
```

**Comment by gdi2290** [comment]
@fesor I added you to the repo since you've been helping out a lot

**Comment by kotmatpockuh** [comment]
@fesor hi, maybe you can provide an example of directive in component-style
?

**Comment by fesor** [comment]
@kotmatpockuh what do you mean?

components - this is just reusable UI components.

directives - act like decorator for components. 

For example you have simple UI component which responsible for lists rendering. It can only render some lists, and provide you... don't know... easy way to define list item template via transcludes. 

Then imagine that we need to add on some of lists something like infinite scroll. We can "change" component to add this feature, allowing to disable it via attribute, OR we could "add" directive, which will listen for scroll and ask some action on end of the list. In this case our list component doesn't know anything about infinite scroll.
