### ISSUE TITLE
Add example of testing a component

### ISSUE THREAD

**Issue by timothymalcham** [AngularClass/NG6-starter#56]
It would be helpful to have an example or two of compiling a template so that you can do things like `expect(component.find('element').text()).to.be...`. I'm fairly new to setting up directive tests, and having trouble getting them set up with this starter repo. 

On the same note, what is the best way to turn the template string that is available in the unit test into a testable directive?

**Comment by timothymalcham** [comment]
To give some more details:

I'm trying to compile the template in the `{templateName}.spec.js` file. I've got function set up to compile templates inside the `describe('Template', () =>` block:

```
function getCompiledElement() {
   let element = angular.element(templateName);
   let compiledElement = $compile(element)($scope);
   $scope.$digest();
   return compiledElement;
}
```

When I try logging the result out in the test (Karma runs the test and logs this out):

```
LOG: Object { 
  0: <h1 class="ng-scope">Report Card</h1>, 
  1:,
  2: <report-card-header class="ng-scope"></report-card-header>, 
  3:, 
  4: <br class="ng-scope">, 
  5:, 
  6: <!-- ngRepeat: chiller in vm.Report.report.chillers -->, 
  length: 7
}
```

So it appears that the template isn't getting compiled? Is there a step I'm missing?

**Comment by fesor** [comment]
Well... if you don't interact with DOM directly (by the way you shouldn't), you should check only data exposed from component's controller. So basicly you should test only component's controller.

All this data-binding stuff is angular concern, this is only infrastructure. It is already well tested. From the other side, compiling templates, crawling DOM and so on will make your test suite pretty slow with no benefits.

You may want to check DOM when you are doing E2E tests, but not for unit tests.

**Comment by fesor** [comment]
@timothymalcham I prepare a very simple example of component spec: https://github.com/fesor/todomvc-angular-components/blob/master/src/app/components/todoItem.component.spec.js

Waiting for feedback.

This spec is relying on template declarative nature, so we only should check state of data.
