### ISSUE TITLE
We should add too ngInject

### ISSUE THREAD

**Issue by iranreyes** [AngularClass/NG6-starter#61]

**Comment by gdi2290** [comment]
that's a good idea can you make a pull-request? I'll add you to the repo after we merge the two

**Comment by fesor** [comment]
@iranreyes do you mean ngAnnotate + `"ngInject";" inside injectable functions?

**Comment by iranreyes** [comment]
yeah

**Comment by fesor** [comment]
Yes, we definitely should do it. This is also will cover #38
