### ISSUE TITLE
Cannot find module 'clone-stats'

### ISSUE THREAD

**Issue by tamtakoe** [AngularClass/NG6-starter#65]
node v.5.1.0, Windows 10 x64

I run `npm i` or `npm i clone-stats`, but get error:
```
module.js:340
    throw err;
    ^

Error: Cannot find module 'clone-stats'
```
I removed node-modules folder and reinstalled modules without positive result

**Comment by gdi2290** [comment]
this might be an error for https://github.com/hughsk/clone-stats since the module was made two years ago and we're on Node 5.x.x

**Comment by tamtakoe** [comment]
It is not work in node v. 4.2.2, but I run it in v. 0.11.9

**Comment by fesor** [comment]
Closing this.
