### ISSUE TITLE
Using the new .component() syntax for components

### ISSUE THREAD

**Issue by wormyy** [AngularClass/NG6-starter#70]
So with angular 1.5 around the corner, I think it would be nice to refactor the components to use the new `.compontent()` declaration syntax. You can read more about it here: http://toddmotto.com/exploring-the-angular-1-5-component-method/

What do you think? I think I will give it a shot.

**Comment by gdi2290** [comment]
can you make a pull-request?

**Comment by wormyy** [comment]
I submitted it a few days ago: https://github.com/AngularClass/NG6-starter/pull/72

Any thoughts?
