### ISSUE TITLE
Importing common stylesheets for all components

### ISSUE THREAD

**Issue by baj84** [AngularClass/NG6-starter#74]
Hi,

I have a variables.styl which I want to be accessible in all other stylesheets under their component folder. Is this possible?

Cheers

**Comment by fesor** [comment]
There is several ways of how you can achieve this.

1) use `import` option or webpack's alias to resolve path to your app file. Check for [details](http://stylus-lang.com/docs/js.html#importpath)

2) use `define` option. In this case you can add global variables before compilation. Please [read this](http://stylus-lang.com/docs/js.html#definename-node) for details. stylus-loader has option `define` which should hold hashmap of properties (name => node).

3) Just use webpack aliases to simplify path resolving.
