### ISSUE TITLE
Please don't recommend to block user zooming on mobile

### ISSUE THREAD

**Issue by dmitriz** [AngularClass/NG6-starter#77]
These attributes to block user from zooming is a very hostile practice:

`<meta name="viewport" content="..., maximum-scale=1, user-scalable=no">`

It forces users with impaired vision into reading uncomfortable sized text or leaving the site for good.
It is especially harmful recommendation in a framework with many developers simply copying the files without thinking about the consequences.
If people need to zoom your site, they have a reason to do so and nothing can put them off more if they can't do it. No design is possible to accommodate everyone at the same time, and letting user to zoom is a very simple solution. Why blocking it is simply beyond my understanding. People will leave your site and you won't even know why!

**Comment by gdi2290** [comment]
can you make a pull-request?

**Comment by fesor** [comment]
I suppose we can close this issue since #78 has landed.
