### ISSUE TITLE
Use yeoman for code generation?

### ISSUE THREAD

**Issue by fesor** [AngularClass/NG6-starter#79]
I think this will be much appropriate way to handle components generation in future. Any thoughts?

**Comment by gdi2290** [comment]
I rather have a separate yeoman generator and include it to the readme. One of the benefits with this approach is that it's dead simple to understand and update. When people use yeoman (at least what I've been noticing) it's only to generate the initial project and maybe for components nothing more.

**Comment by fesor** [comment]
Hm... I agree with that. Maybe it will be better to prepare separate yeoman generator based on this starter...

**Comment by gdi2290** [comment]
if you want to start it and we can transfer it to AngularClass GitHub org then mention it in the readme

**Comment by fesor** [comment]
Got it. Closing this.
