### ISSUE TITLE
Uncaught TypeError: _angular2.default.module(...).component is not a function

### ISSUE THREAD

**Issue by diit** [AngularClass/NG6-starter#81]
While running ```npm test ```
I get:
```
Chrome 47.0.2526 (Windows 10 0.0.0) ERROR
  Uncaught TypeError: _angular2.default.module(...).component is not a function
  at C:/xampp/projects/project/spec.bundle.js:31716 <- webpack:/C:/xampp/projects/project/client/app/common/hero/hero.js:5:0
```

**Comment by fesor** [comment]
you have two solutions:

1) update to angular 1.5
2) add this line to every file with module definition:

```javascript
import 'angular-component';
```

p.s. This problem intoduced in #72

**Comment by mattycraig** [comment]
Adding `import angularComponent from 'angular-component';` to spec.bundle.js solved this for me.

**Comment by fesor** [comment]
@mattycraig I don't know is it good to require it in `spec.bundle.js`. Will think on fixing this.

**Comment by fesor** [comment]
@diit this issue doesn't solved yet.

**Comment by diit** [comment]
Of course - however the solution proposed through updating angular solve
the issue for me.

On Sat, Jan 9, 2016 at 10:51 AM, Sergey Protko <notifications@github.com>
wrote:

> @diit <https://github.com/diit> this issue doesn't solved yet.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/AngularClass/NG6-starter/issues/81#issuecomment-170254196>
> .
>



-- 
*Thanks,*
Dale Inverarity
