### ISSUE TITLE
Adding "bootstrap-loader", only one instance of babel-polyfill error.

### ISSUE THREAD

**Issue by diit** [AngularClass/NG6-starter#82]
Added this to default project: https://github.com/shakacode/bootstrap-loader

imported into app.js and got:
```
stream.js:74
      throw er; // Unhandled stream error in pipe.
      ^
 Error: Error: only one instance of babel-polyfill is allowed
```

Any idea on best way to include bootstrap into project?

**Comment by fesor** [comment]
You don't need any `bootstrap-loader`s.

```
import bootstrap from 'angular-ui-bootstrap';
```

p.s. This should be in wiki.
