### ISSUE TITLE
Component binding is not working as expected

### ISSUE THREAD

**Issue by juhamust** [AngularClass/NG6-starter#83]
It may be due to fact that the repository is missing an example, but component binding is not working as expected: The parameters are not passed/bind to controllers.
```html
<hero value="foo"></hero>
```
```javascript

// hero.component.js
import template from './hero.html';
import controller from './hero.controller';

let heroComponent = {
  restrict: 'E',
  bindings: {
    value: '@'
  },
  template,
  controller,
  controllerAs: 'vm'
};
```
```javascript
class HeroController {
  constructor() {
    this.name = 'hero';
    console.log(this.value); // undefined!
  }
}
```
```html
<section class="hero">
  <h1>This is the NG6 starter</h1>
  <!-- Value is also undefined within template -->
  <h3>You can find me inside {{ vm.name }}.html {{ vm.value }}</h3>
</section>
```

A bug or user error?

**Comment by juhamust** [comment]
Apparently the issue is in `angular-component` module: With version 0.0.3 I'm able to get the expected outcome. So just ensure you'll depend on >= 0.0.3

https://github.com/toddmotto/angular-component/issues/9

Feel free to close. However, it would make no harm to this boilerplate to have an example about how to pass values to a component?

**Comment by fesor** [comment]
@juhamust thanks.

**Comment by michalpanek** [comment]
I cannot use bindings:( I have angular 1.5.7, but component's bindings apparently not working. 

`import template from './invite.html';
import controller from './invite.controller';
import './invite.scss';

let inviteComponent = {
  restrict: 'E',
  bindings: {
    onChangeUserName: '&',
    userName: '<'
  },
  template,
  controller,
  controllerAs: 'vm'
};

export default inviteComponent;
`
Should not this work with angular 1.5.7? 
How I can use bindings in component?

**Comment by fesor** [comment]
@manekinekko it should work. Please provide how you use this component

**Comment by michalpanek** [comment]
I have component about from origin source from starter:

`import template from './about.html';
import controller from './about.controller';
import './about.scss';

let aboutComponent = {
  restrict: 'E',
  bindings: {},
  template,
  controller,
  controllerAs: 'vm'
};

export default aboutComponent;
`

controller: 

`class AboutController {
  constructor(UserService) {
    this.name = 'about';
    this.userService = UserService;
  }
  
  $onInit() {
    //userService is working, get proper data
    this.userNameFromService = this.userService.getUser().name;
    this.userName = 'tomek';
  }

  changeUserName({newUserName}) {
    console.log('click');
    console.log(newUserName);
  }
}

AboutController.$inject = ['UserService'];

export default AboutController;`

In about html template I use <invite> component, try pass the data by bindings attribute:

`<section>
  About us.
  name: <input type="text" placeholder="name of invitiation user" ng-model="vm.userName">
  <invite on-changes-user-name="vm.changeUserName($event)" userName="vm.userName"></invite>
</section>`

-------------------------
component <invite>:
`import template from './invite.html';
import controller from './invite.controller';
import './invite.scss';

let inviteComponent = {
  restrict: 'E',
  bindings: {
    onChangeUserName: '&',
    userName: '<'
  },
  template,
  controller,
  controllerAs: 'vm'
};

export default inviteComponent;
`

controller <invite> component: 
`class InviteController {
  constructor() {
    this.name = 'invite';
  }

  $onInit() {
    console.log(this.userName);
  }

  $onChanges(changes) {
    console.log('changes');
    if (changes.userName) {
      this.userName = Object.assign({}, this.userName);
    }
  }

  sendNameUp() {
    this.onChangeUserName({
      $event: {
        name: this.userNameInput
      }
    });
  }
}
`
<invite> component html template:

`<div>
  <h1>{{ vm.name }}</h1>
  <h2>user name: {{ vm.userName  }}</h2>
  input new name: <input type="text" placeholder="new name" ng-model="vm.userNameInput">
  <button ng-click="vm.sendNameUp()">send name up</button>
</div>`

In components.js file I have:

`import angular from 'angular';
import Home from './home/home';
import About from './about/about';
import Invite from './about/invite/invite';
import ListArticles from './home/list-articles/list-articles';

let componentModule = angular.module('app.components', [
  ListArticles.name,
  Home.name,
  About.name,
  Invite.name
]);

export default componentModule;
`

I've been trying figure out what is going wrong for couple of the last days, reinstall angularjs, even try to add angular-component module from todd motto. Gulp version 5.10.1

What am I doing wrong?

**Comment by michalpanek** [comment]
Is work as it should, but in original project ng6 starer. Before I used [ng6 starter with sass ](https://github.com/AngularClass/NG6-starter). I don't now if in that project is something wrong. Anyway I must change styl to scss. But bindings work:)

**Comment by brcaswell** [comment]
@michalpanek your `InviteController` controller `onChange` logic

```
  if (changes.userName) {
      this.userName = Object.assign({}, this.userName);
  }
```
should be,
```
  if (changes.userName) {
    let userNameChanges: IChangesObject = changes[username];
    let currentUserName = userNameChanges.currentValue;
    let previousUserName = userNameChanges.previousValue;
    
    this.userName = Object.assign({}, currentUserName );
    // or, 
    // Object.assign(this.username, currentUserName );
  }
```

you're essentially not accounting for the change and simply shallow copying the same value to itself.

**Comment by brcaswell** [comment]
also, I'm not sure of the `Object.assign` usage for an object with seemingly no enumerable properties.. `userName` in this instance... I typically use it for export class type instances only, (referential vs value type thinking).
