### ISSUE TITLE
Project depends on old version of webpack-stream that is having issues with fonts

### ISSUE THREAD

**Issue by juhamust** [AngularClass/NG6-starter#92]
Webpack build produces broken font files due to this issue:

https://github.com/shama/webpack-stream/commit/6169c96fa6d666568bf1df6d9d304fa5c8fee8fd

Therefore, update the `webpack-stream` dependency to latest version.

**Comment by fesor** [comment]
I prepared PR (#90) which uses webpack instead of webpack-stream.

**Comment by fesor** [comment]
Closing this since we don't use `webpack-stream` anymore.
