### ISSUE TITLE
Inclusion to Awesome AngularJS list?

### ISSUE THREAD

**Issue by dmitriz** [AngularClass/NG6-starter#96]
I would like to suggest adding this project to [Awesome AngularJS](https://github.com/gianarb/awesome-angularjs#seed-projects) (and possibly other) lists.

That list has sadly mostly outdated Angular projects, so this one would be a great addition.

**Comment by gdi2290** [comment]
@dmitriz can you make a pull-request on that repo to include this one?

**Comment by fesor** [comment]
Closing this since https://github.com/gianarb/awesome-angularjs/issues/68 is merged.
