### ISSUE TITLE
error importing font-awesome and bootstrap

### ISSUE THREAD

**Issue by i-am-dror** [AngularClass/NG6-starter#99]
i get the following errors:

ERROR in ./~/css-loader!./~/stylus-loader!./client/app/app.styl
Module not found: Error: Cannot resolve 'file' or 'directory' ./node_modules/bootstrap-stylus/stylus/bootstrap.styl in /Users/dror/workspace/mng-ui/dashboard/client/app
 @ ./~/css-loader!./~/stylus-loader!./client/app/app.styl 3:10-117

**Comment by fesor** [comment]
Please read stylus-loader documentation, they have example in "Usage" section.

Also note than `bootstrap-stylus` is deprecated, use `bootstrap-styl` instead.

**Comment by i-am-dror** [comment]
i'm using bootstrap-styl
that resolves an error.
is there an example project with bootstrap imported?

**Comment by fesor** [comment]
@i-am-dror i want to add wiki page about this topic. Personally I use angular-ui-bootstrap with less in my projects.

**Comment by i-am-dror** [comment]
i have no problem requiring the angular-ui-bootstrap module,
the problem is importing the styl, i get error regarding the inner dependencies.
all of the files are directed to "bootstrap/..." and its not resolving.

**Comment by PedroEsperanca** [comment]
Did anyone figure out how to load bootstrap yet? It's proving to be very challenging.

The documentations aren't clear and the paths seem to be wrong

**Comment by fesor** [comment]
@PedroEsperanca Please see https://github.com/AngularClass/NG6-starter/pull/129 - there is an example.

**Comment by PedroEsperanca** [comment]
thanks for the quick response @fesor !
My difficulty was with bootstrap-styl, but I ended up using bootstrap-sass since it has a larger usage

**Comment by roymj88** [comment]
Hi, there is no mention as to how we can include font awesome??
